#!/usr/bin/env python
import time
import argparse
import serial
import sys
#import json

OUT_STREAM  = sys.stdout

DEFAULT_BAUDRATE = 9600

parser = argparse.ArgumentParser()

parser.add_argument("-p","--path", required=True, help="path to the sensor")
parser.add_argument("-v", "--verbose", action="store_true", help="increase output verbosity")

args = parser.parse_args()
ser = None

try:
    # open serial port
    ser = serial.Serial(args.path, baudrate=DEFAULT_BAUDRATE, dsrdtr=True)
    time.sleep(4.0)
    ser.flushInput()
    # send command and retrieve response
    #ser.write("LED_STATUS\n")
    ser.write("MEAS_DEPTH_VALUES\n")
    time.sleep(0.1)
    resp = ser.readline().strip()
    #print resp
    x=resp.strip()
    x=x.split(",")
    temp=float(x[0])/100.
    humidity=float(x[1])/100.
    OUT_STREAM.write("{")
    OUT_STREAM.write("\"temp\":")
    OUT_STREAM.write(str(temp))
    OUT_STREAM.write(",\"humidity\":")
    OUT_STREAM.write(str(humidity))
    OUT_STREAM.write("}")
    #if args.verbose:
    #    print "LED status via path {}: {}".format(args.path, sensor_val)
    #else:
    #    print sensor_val
finally:
    ser.close()
